import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import {Squares2X2Icon, MagnifyingGlassIcon, MicrophoneIcon} from "@heroicons/react/24/solid"
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
    const searchInputRef = useRef(null)
    const router = useRouter()

    const Search = (e) => {
        e.preventDefault()
        const term = searchInputRef.current.value

        if(!term) return

        router.push(`/search?term=${term}`)

    }   

	return (
		<div className="flex flex-col items-center justify-center h-screen">
			<Head>
				<title>Google Clone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className="flex w-full p-5 justify-between text-sm text-gray-700">
				{/* Left */}
				<div className='space-x-4 items-center hidden sm:flex'>
					<p className="link">About</p>
					<p className="link">Store</p>
				</div>

				{/* right */}
				<div className='flex space-x-4 items-center float-right justify-end w-full'>
					<p className="link">Gmail</p>
					<p className="link">Images</p>

                {/* Icon */}
                <Squares2X2Icon className="h-10 w-10 p-2 hover:bg-gray-300 cursor-pointer rounded-full" />


                {/* Avatar */}
                <Avatar url="/images/eg.jpeg" />
				</div>
			</header>

			{/* Body */}
            <form className="flex flex-col w-4/5 flex-grow items-center  mx-auto mt-44">
                <img
                src="https://www.google.co.uk./images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
                height="100"
                width="300"                
                />

                <div className="flex gap-2 w-full max-w-md sm:max-w-xl lg:max-w-2xl shadow-md focus-within:shadow-md hover:shadow-gray-300 rounded-full p-2 justify-between border border-gray-200 ">
                    <MagnifyingGlassIcon className="w-6 h-6 text-gray-400" />
                    <input ref={searchInputRef} type="text" className="flex-1 outline-none border-none" />
                    <MicrophoneIcon className="w-6 h-6 text-gray-400" />
                </div>

                <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:flex-row sm:space-y-0 sm:space-x-4">
                    <button onClick={Search}  className="btn">Google Search</button>

                    <button onClick={Search} className="btn">I'm Feeling Lucky</button>
                </div>
            </form>

			{/* Footer */}
            <Footer />
		</div>
	);
}
